includedir=$(prefix)/include/

build:

install: $(includedir)/Atmosphere.H

$(includedir)/Atmosphere.H: Atmosphere.H
	cp Atmosphere.H $(includedir)

uninstall:
	- rm -f $(includedir)/Atmosphere.H

clean:

